services:
  frontend:
    image: job-assistant-frontend:local

    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "127.0.0.1:8081:80"

    depends_on:
      backend:
        condition: service_healthy

    restart: unless-stopped
    init: true
    stop_grace_period: 10s