"""create auth tables

Revision ID: 9a899c1d39da
Revises: a2b89ad42d65
Create Date: 2026-09-30 09:19:21.844724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9a899c1d39da'
down_revision: Union[str, Sequence[str], None] = 'a2b89ad42d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(trim(email)) AND length(email) > 0', name=op.f('ck_users_email_normalized')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('conversation_ownerships',
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_conversation_ownerships_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('thread_id', name=op.f('pk_conversation_ownerships'))
    )
    op.create_index('ix_conversation_ownerships_user_id_created_at', 'conversation_ownerships', ['user_id', 'created_at'], unique=False)
    op.create_table('cv_ownerships',
    sa.Column('cv_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_cv_ownerships_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('cv_id', name=op.f('pk_cv_ownerships'))
    )
    op.create_index('ix_cv_ownerships_user_id_created_at', 'cv_ownerships', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove auth tables."""
    op.drop_index('ix_cv_ownerships_user_id_created_at', table_name='cv_ownerships')
    op.drop_table('cv_ownerships')
    op.drop_index('ix_conversation_ownerships_user_id_created_at', table_name='conversation_ownerships')
    op.drop_table('conversation_ownerships')
    op.drop_table('users')
