"""create jobs table

Revision ID: a2b89ad42d65
Revises: 
Create Date: 2026-08-25 11:57:33.962412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2b89ad42d65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('work_mode', sa.String(length=50), nullable=False),
    sa.Column('seniority_level', sa.String(length=50), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('salary_period', sa.String(length=50), nullable=False),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(salary_min IS NULL AND salary_max IS NULL) OR salary_currency IS NOT NULL', name=op.f('ck_jobs_salary_currency_required')),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name=op.f('ck_jobs_salary_range')),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_jobs_source_source_job_id')
    )
    op.create_index('ix_jobs_content_hash', 'jobs', ['content_hash'], unique=False)
    op.create_index('ix_jobs_employment_type', 'jobs', ['employment_type'], unique=False)
    op.create_index('ix_jobs_seniority_level', 'jobs', ['seniority_level'], unique=False)
    op.create_index('ix_jobs_source_posted_at', 'jobs', ['source', 'posted_at'], unique=False)
    op.create_index('ix_jobs_work_mode', 'jobs', ['work_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_work_mode', table_name='jobs')
    op.drop_index('ix_jobs_source_posted_at', table_name='jobs')
    op.drop_index('ix_jobs_seniority_level', table_name='jobs')
    op.drop_index('ix_jobs_employment_type', table_name='jobs')
    op.drop_index('ix_jobs_content_hash', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
